// Shared blog data (used by /blog and /blog/[slug])
const BLOG_TAGS = ["Všetko", "Leasing", "Akontácia", "Tipy"];

const TAG_COLORS = {
  "Leasing": "bg-blue-100 text-blue-800",
  "Akontácia": "bg-emerald-100 text-emerald-800",
  "Tipy": "bg-violet-100 text-violet-800",
};

const BLOG_POSTS = [
  {
    slug: "5-tipov-financovanie",
    tag: "Tipy",
    title: "5 tipov, ako sa pripraviť na žiadosť o financovanie auta",
    excerpt: "Schválenie ide rýchlejšie, ak máte všetko nachystané vopred. Prehľad toho, čo kontroluje banka aj leasingová spoločnosť.",
    date: "26. máj 2026",
    readTime: "4 min",
    color: "from-violet-500 to-purple-600",
    image: "img/blog-5tipov.jpeg",
    isVideo: false,
    featured: true,
  },
  {
    slug: "akontacia-ano-nie",
    tag: "Akontácia",
    title: "Bez akontácie alebo s akontáciou? Čo sa viac oplatí?",
    excerpt: "Akontácia môže byť 0 % aj 50 %. Aký vplyv má na mesačnú splátku a celkové náklady?",
    date: "22. máj 2026",
    readTime: "5 min",
    color: "from-emerald-500 to-teal-600",
    image: "img/blog-akontacia.jpeg",
    isVideo: false,
  },
  {
    slug: "leasing-vs-uver",
    tag: "Leasing",
    title: "Leasing vs spotrebný úver na auto. Aký je rozdiel?",
    excerpt: "Pri kúpe auta na splátky máte dve hlavné možnosti. Vysvetľujeme, kedy sa oplatí ktorá.",
    date: "18. máj 2026",
    readTime: "5 min",
    color: "from-blue-500 to-indigo-600",
    image: "img/blog-leasing-uver.jpeg",
    isVideo: false,
  },
  {
    slug: "schvalenie-leasingu-2026",
    tag: "Leasing",
    title: "Ako funguje schválenie leasingu v roku 2026?",
    excerpt: "Leasing nie je komplikovaný. Vysvetľujeme, čo banky sledujú a ako sa pripraviť na schválenie.",
    date: "14. máj 2026",
    readTime: "4 min",
    color: "from-sky-500 to-blue-600",
    image: "img/blog-schvalenie.jpeg",
    isVideo: false,
  },
  {
    slug: "auto-na-splatky-tipy",
    tag: "Tipy",
    title: "Ako si vybrať správne auto na splátky? Na toto si dajte pozor",
    excerpt: "Pozrieť sa len na cenu auta je chyba. Čo sledovať pri výbere, aby splátky fungovali dlhodobo.",
    date: "10. máj 2026",
    readTime: "5 min",
    color: "from-amber-500 to-orange-600",
    image: "img/blog-vyber-auta.jpeg",
    isVideo: false,
  },
  {
    slug: "mesacna-splatka",
    tag: "Tipy",
    title: "Čo všetko ovplyvňuje mesačnú splátku auta?",
    excerpt: "Prečo má niekto nižšiu splátku a niekto vyššiu? Všetky faktory, ktoré vstupujú do výpočtu.",
    date: "6. máj 2026",
    readTime: "4 min",
    color: "from-rose-500 to-pink-600",
    image: "img/blog-splatka.jpeg",
    isVideo: false,
  },
  {
    slug: "operativny-leasing",
    tag: "Leasing",
    title: "Operatívny leasing. Pre koho sa dnes oplatí?",
    excerpt: "Operatívny leasing je čoraz populárnejší aj na Slovensku. Pre koho má zmysel a čím sa líši od finančného?",
    date: "2. máj 2026",
    readTime: "5 min",
    color: "from-indigo-500 to-blue-600",
    image: "img/blog-operativny.jpeg",
    isVideo: false,
  },
  {
    slug: "auto-na-splatky-preco",
    tag: "Tipy",
    title: "Prečo dnes veľa ľudí rieši auto radšej na splátky?",
    excerpt: "Ľudia kupujú autá na splátky čoraz častejšie. Prečo to dáva zmysel a čo treba sledovať pri nastavení financovania.",
    date: "28. apríl 2026",
    readTime: "4 min",
    color: "from-cyan-500 to-blue-500",
    image: "img/blog-preco-splatky.jpeg",
    isVideo: false,
  },
];

const BLOG_BODIES = {
  "5-tipov-financovanie": [
    { type: "p", text: "Veľa ľudí dnes rieši financovanie auta cez leasing alebo úver, no často nevedia, čo všetko si leasingová spoločnosť alebo banka kontroluje. Práve preto sme pripravili jednoduchý prehľad toho, čo môže výrazne pomôcť pri schválení financovania auta." },
    { type: "h2", text: "1. Mať poriadok vo financiách" },
    { type: "p", text: "Ak má klient veľa omeškaných splátok alebo neplatené záväzky, môže to negatívne ovplyvniť schválenie. Dôležitý je aj čistý register a pravidelný príjem." },
    { type: "h2", text: "2. Správny výber auta" },
    { type: "p", text: "Nie každé auto má rovnaké podmienky financovania. Novšie vozidlá majú často lepšie možnosti leasingu, nižšie mesačné splátky a jednoduchšie schválenie." },
    { type: "h2", text: "3. Akontácia" },
    { type: "p", text: "Aj menšia akontácia môže pomôcť znížiť mesačné splátky a zlepšiť podmienky financovania. Nie je podmienkou, ale môže veci urýchliť." },
    { type: "h2", text: "4. Doklady vopred" },
    { type: "p", text: "Pripravte si doklady skôr, ako ich niekto požiada. Zvyčajne ide o doklad totožnosti, potvrdenie o príjme a výpis z účtu. Živnostníci prikladajú daňové priznanie." },
    { type: "h2", text: "5. Komunikácia bez zamlčovania" },
    { type: "p", text: "Ak máte v minulosti nejakú skvrnu v registri alebo existujúci úver, povedzte to na začiatku. Skrývanie situáciu nezlepší, naopak. Riešenia existujú aj pre zložitejšie profily." },
    { type: "p", text: "Na automesacne.sk klientom vždy poradíme, čo pripraviť ešte pred podaním žiadosti. Práve osobný prístup a normálna komunikácia sú dôvod, prečo sa na nás klienti často vracajú." },
  ],
  "akontacia-ano-nie": [
    { type: "p", text: "Financovanie auta bez akontácie je dnes veľmi populárne hlavne medzi mladými ľuďmi, rodinami a podnikateľmi. Veľa klientov nechce investovať všetky úspory naraz a radšej si nechajú finančnú rezervu." },
    { type: "h2", text: "Financovanie bez akontácie" },
    { type: "p", text: "Výhodou financovania bez akontácie je hlavne rýchly prístup k autu bez veľkej vstupnej investície. Na druhej strane môže byť mesačná splátka o niečo vyššia a celkové preplatenie väčšie." },
    { type: "h2", text: "Financovanie s akontáciou" },
    { type: "p", text: "Ak klient zaplatí akontáciu, často získa nižšie mesačné splátky a lepšie podmienky leasingu. Pre niekoho je preto výhodnejšie vložiť časť financií na začiatku a následne mať nižšiu mesačnú záťaž." },
    { type: "quote", text: "Nie je univerzálna správna odpoveď. Záleží od vašej aktuálnej finančnej situácie a preferencií." },
    { type: "p", text: "Na automesacne.sk sa snažíme každému klientovi pripraviť viac možností financovania. Niekomu dáva väčší zmysel nulová akontácia, inému zase nižšie splátky cez vyššiu akontáciu. Dôležité je, aby financovanie bolo nastavené rozumne a klient sa cítil komfortne aj dlhodobo." },
  ],
  "leasing-vs-uver": [
    { type: "p", text: "Mnoho ľudí dnes nevie, aký je presný rozdiel medzi leasingom a spotrebným úverom na auto. Obe možnosti majú svoje výhody a záleží hlavne od konkrétnej situácie klienta." },
    { type: "h2", text: "Leasing" },
    { type: "p", text: "Pri leasingu je vozidlo počas splácania vo vlastníctve leasingovej spoločnosti. Klient auto využíva a po splatení môže prejsť do jeho vlastníctva. Leasing býva veľmi populárny pri novších autách, firemných vozidlách alebo financovaní na IČO." },
    { type: "h2", text: "Spotrebný úver" },
    { type: "p", text: "Pri spotrebnom úvere býva auto často od začiatku napísané priamo na klienta. Niektorým ľuďom to vyhovuje viac hlavne z pohľadu flexibility. Spotrebný úver zas často využívajú ľudia pri lacnejších autách alebo keď chcú jednoduchšie podmienky." },
    { type: "h2", text: "Čo rozhoduje o výbere" },
    { type: "ul", items: [
      "Plánujete auto na IČO alebo pre firmu? Leasing má daňové výhody.",
      "Chcete mať auto okamžite vo vlastníctve? Spotrebný úver.",
      "Nové alebo ojazdené auto? Leasing sa hodí viac na novšie vozidlá.",
      "Záleží vám na nižšom úroku? Leasing ho zvyčajne ponúka.",
    ] },
    { type: "p", text: "Na automesacne.sk klientom všetko vysvetlíme jednoducho a pripravíme viac možností. Naším cieľom nie je klientovi niečo nasilu predať, ale pomôcť mu nájsť riešenie, ktoré bude dlhodobo fungovať." },
  ],
  "schvalenie-leasingu-2026": [
    { type: "p", text: "Veľa ľudí má stále pocit, že leasing je komplikovaný proces plný papierovačiek. Realita je dnes úplne iná." },
    { type: "h2", text: "Čo leasingové spoločnosti kontrolujú" },
    { type: "p", text: "Vo väčšine prípadov sa dá financovanie auta vybaviť veľmi rýchlo. Dôležitý je hlavne pravidelný príjem, dobrá platobná história a správne pripravené dokumenty." },
    { type: "p", text: "Leasingové spoločnosti dnes často kontrolujú registre, existujúce úvery a celkovú finančnú situáciu klienta. Práve preto je dobré pripraviť si všetko vopred." },
    { type: "h2", text: "Čo ak som mal v minulosti problém so splátkou?" },
    { type: "p", text: "Klienti sa často boja, že keď mali v minulosti problém so splátkou, automaticky nemajú šancu. Každý prípad je však individuálny a veľa závisí od aktuálnej situácie." },
    { type: "quote", text: "Neodkladajte žiadosť len preto, že máte obavy. Každý prípad sa posudzuje individuálne." },
    { type: "p", text: "Na automesacne.sk komunikujeme s klientmi normálne a ľudsky. Vysvetlíme celý proces, poradíme čo pripraviť a snažíme sa nájsť čo najlepšie riešenie." },
  ],
  "auto-na-splatky-tipy": [
    { type: "p", text: "Kúpa auta je dnes pre veľa ľudí jedna z najväčších finančných rozhodnutí. Nie každý chce alebo vie zaplatiť celé auto naraz, a práve preto je financovanie auta cez leasing alebo úver čoraz populárnejšie." },
    { type: "h2", text: "Nepozerajte sa len na cenu auta" },
    { type: "p", text: "Veľa klientov robí chybu, že sa pozerajú iba na cenu auta. V realite je omnoho dôležitejšia mesačná splátka, celkové náklady a to, ako bude financovanie fungovať dlhodobo. Auto môže vyzerať cenovo výhodne, no ak má vysoké servisné náklady alebo nevýhodné financovanie, výsledok môže byť úplne opačný." },
    { type: "h2", text: "Na čo sa sústrediť pri výbere" },
    { type: "ul", items: [
      "Mesačné náklady vrátane poistenia a servisu",
      "Spotrebu paliva pri bežnej jazde",
      "Dostupnosť a cenu servisu",
      "Spoľahlivosť konkrétneho modelu",
      "Budúcu hodnotu auta pri prípadnom predaji",
    ] },
    { type: "p", text: "Mnoho ľudí dnes rieši hlavne SUV, rodinné autá alebo firemné vozidlá na leasing. Veľmi populárne sú aj financovania bez akontácie, kde klient nemusí vložiť veľkú sumu na začiatku." },
    { type: "p", text: "Na automesacne.sk klientom pomáhame nájsť riešenie, ktoré nebude vyzerať dobre len prvý mesiac, ale bude fungovať aj dlhodobo. Každému pripravíme individuálne možnosti financovania, vysvetlíme rozdiel medzi leasingom a úverom a poradíme, čo sa viac oplatí." },
  ],
  "mesacna-splatka": [
    { type: "p", text: "Veľa klientov sa nás pýta jednoduchú otázku: prečo má niekto nižšiu splátku a niekto vyššiu? Pravda je taká, že mesačnú splátku ovplyvňuje viacero faktorov a nejde iba o cenu auta." },
    { type: "h2", text: "Akontácia" },
    { type: "p", text: "Jedným z najdôležitejších faktorov je akontácia. Ak klient vloží vyššiu prvú platbu, mesačné splátky môžu byť výrazne nižšie. Veľa ľudí však dnes preferuje financovanie bez akontácie, aby si zachovali finančnú rezervu." },
    { type: "h2", text: "Dĺžka financovania" },
    { type: "p", text: "Kratšie splácanie znamená vyššiu mesačnú splátku, ale nižšie celkové preplatenie. Dlhšie financovanie zas znižuje mesačnú záťaž, no celkovo zaplatíte viac." },
    { type: "h2", text: "Čo ešte leasingové spoločnosti sledujú" },
    { type: "ul", items: [
      "Príjem klienta a jeho stabilitu",
      "Existujúce úvery a splátky",
      "Register dlžníkov",
      "Pracovný pomer (zamestnanec, SZČO, s.r.o.)",
      "Celkovú bonitu",
    ] },
    { type: "p", text: "Veľa klientov si myslí, že keď mali v minulosti problém, automaticky nemajú šancu. Každý prípad je však individuálny a práve preto je dôležitá komunikácia a správne nastavenie financovania." },
    { type: "p", text: "Na automesacne.sk sa snažíme klientom pripraviť riešenie, ktoré bude reálne zvládnuteľné aj dlhodobo." },
  ],
  "operativny-leasing": [
    { type: "p", text: "Operatívny leasing je na Slovensku čoraz populárnejší hlavne medzi podnikateľmi a firmami. Veľa ľudí však stále presne nevie, ako funguje a aké má výhody." },
    { type: "h2", text: "Ako funguje operatívny leasing" },
    { type: "p", text: "Pri operatívnom leasingu klient auto v podstate využíva podobne ako prenájom. Platí si mesačné splátky, jazdí na novom aute a po skončení leasingu môže vozidlo jednoducho vymeniť za nové." },
    { type: "h2", text: "Výhody operatívneho leasingu" },
    { type: "p", text: "Veľkou výhodou operatívneho leasingu je predvídateľnosť nákladov. Firmy presne vedia, koľko budú mesačne platiť a nemusia riešiť pokles hodnoty auta pri predaji ani väčšie opravy." },
    { type: "h2", text: "Pre koho je vhodný" },
    { type: "ul", items: [
      "Firmy, ktoré potrebujú flotilu vozidiel",
      "Živnostníci, ktorí chcú auto na IČO bez veľkých vstupných nákladov",
      "Manažéri, ktorí chcú jazdiť na novšom aute každé 3-4 roky",
      "Súkromné osoby, ktorým vyhovuje prenájomný model",
    ] },
    { type: "p", text: "Na automesacne.sk klientom vysvetlíme rozdiel medzi operatívnym a finančným leasingom a pomôžeme vybrať možnosť, ktorá bude najlepšie vyhovovať ich situácii." },
  ],
  "auto-na-splatky-preco": [
    { type: "p", text: "Doba sa mení a spolu s ňou aj spôsob, akým ľudia kupujú autá. Kedysi bolo bežné šetriť roky na auto alebo kupovať staršie vozidlá za hotovosť. Dnes však veľa ľudí preferuje financovanie auta cez leasing alebo úver." },
    { type: "h2", text: "Komfort a finančná flexibilita" },
    { type: "p", text: "Hlavným dôvodom je komfort a finančná flexibilita. Klient nemusí investovať všetky svoje úspory naraz a zároveň môže jazdiť na bezpečnejšom, modernejšom a spoľahlivejšom aute." },
    { type: "h2", text: "Čo ľudia riešia najčastejšie" },
    { type: "ul", items: [
      "Bezpečnosť pre rodinu",
      "Nižšiu spotrebu a prevádzkové náklady",
      "Predvídateľné mesačné náklady bez nečakaných opráv",
      "Komfort a moderné technológie",
      "Garancia spolehlivosti nového vozidla",
    ] },
    { type: "p", text: "Práve preto je auto na splátky pre veľa ľudí rozumnejšie riešenie ako kúpa veľmi starého auta, do ktorého budú neustále investovať peniaze." },
    { type: "p", text: "Na automesacne.sk sa snažíme klientom ukázať, že financovanie auta nemusí byť komplikované ani stresujúce. Dôležité je len správne nastavenie splátok a férový prístup." },
  ],
};

function getRelatedPosts(currentSlug, count = 3) {
  return BLOG_POSTS.filter(p => p.slug !== currentSlug).slice(0, count);
}

function getPostBySlug(slug) {
  return BLOG_POSTS.find(p => p.slug === slug) || null;
}
